### ISSUE TITLE
Feature request: enhance error reporting for JSON responses

### ISSUE THREAD

**Issue by morgen-peschke** [gkulasik/grpc_assistant_server#9]
Currently, if the server response is non-success, the result looks like this:
```
{
    "error": "ERROR:\n  Code: Unavailable\n  Message: \n"
}
```

This is useful, however it does look like something that could have originated with the server. An alternate format may be more clear, possibly along these lines:
```
{
   "grpc_error": {
      "code": "Unavailable",
      "message": ""
    }
}
```

**Comment by gkulasik** [comment]
The "error" field currently captures the output from the shell when executing the grpcurl command, it may be plain text or JSON formatted. I agree the format you proposed is cleaner and something to look into, it will likely require an error parser to format GRPC errors vs just plain text system errors.
